inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  # `always` will always add the frozen string literal comment to a file
  # regardless of the Ruby version or if `freeze` or `<<` are called on a
  # string literal. If you run code against multiple versions of Ruby, it is
  # possible that this will create errors in Ruby 2.3.0+.
  EnforcedStyle: always

Style/HashSyntax:
  EnforcedStyle: ruby19
