inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - gemfiles/**/*

Metrics/LineLength:
  Max: 140

# ¯\_(ツ)_/¯
# ʕノ•ᴥ•ʔノ ︵ ┻━┻
# ( ͡° ͜ʖ ͡°)
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/StringLiterals:
  EnforcedStyle: double_quotes
