inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - gemfiles/**/*

Metrics/LineLength:
  Max: 140

# Can't do without a little table-flip there ;)
Style/AsciiComments:
  Exclude:
    - 'test/scope_test.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/StringLiterals:
  EnforcedStyle: double_quotes
