language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

before_install:
  - gem update --system

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/rails_6.0.gemfile
      rvm: 2.4
