language: ruby
sudo: false
dist: trusty
cache: bundler
script: "bundle exec rake test"

rvm:
  - 2.1
  - 2.2.6
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.1.gemfile
