language: ruby
cache: bundler
script: "bundle exec rake"

rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

before_install:
  - gem install rubygems-update && update_rubygems
  # Rails 4.2 doesn't support bundler 2.0, so we need to lock bundler to
  # v1.17.3. This is just for Ruby 2.5 which ships with bundler 2.x on Travis
  # CI while Ruby 2.6 does not.
  - yes | rvm @global do gem uninstall bundler --all
  - yes | rvm @global do gem install bundler -v 1.17.3 || true

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1.gemfile
